type: group
fields:
  grid_section_headline:
    type: headline
    label: Component Grid Settings

  grid_column_preset:
    label: Grid Column Preset
    extends: grid_column_preset  

  grid_column_start_class:
    extends: auf_grid/fields/grid_column_start_class
    width: 1/2
    when:
      grid_column_preset: grid__column--custom
  
  grid_column_end_class:
    extends: auf_grid/fields/grid_column_end_class
    width: 1/2
    when:
      grid_column_preset: grid__column--custom


  # ALIGN & JUSTIF SELF

  grid_align_show_fields:
    label: Align & Justify Self
    type: toggle
    width: 2/6
    text:
      - hide
      - show

  grid_align_self_class:
    label: Align Self (vertical)
    type: grid_align_self
    width: 2/6
    when:
      grid_align_show_fields: true
  
  grid_justify_self_class:
    label: Justify Self (vertical)
    type: grid_justify_self
    width: 2/6
    when:
      grid_align_show_fields: true


  # CONTAINER GRID CLASSES FOR ITEMS

  container_grid_settings:
    type: headline
    label: Container Component Grid Settings

  container_grid_class:
    type: select
    label: Sub-Grid Type
    default: grid
    options:
      grid: grid
      inline-grid: inline-grid

  container_inline_grid_items_span_class: 
    label: Inline Grid Items Span Class
    type: inline_grid_items_span_classes
    when: 
      container_grid_type: inline-grid


  container_show_align_and_justify_items_classes:
    label: Align & Justify Items
    type: toggle
    width: 2/6
    text:
      - hide
      - show


  container_align_items_class:
    label: Align Items (vertical)
    type: grid_align_items
    width: 2/6
    when:
      container_show_align_and_justify_items_classes: true
  
  container_justify_items_class:
    label: Justify Items (horizontal)
    type: grid_justify_items
    width: 2/6
    when:
      container_show_align_and_justify_items_classes: true