type: group
fields:
  grid_section_headline:
    type: headline
    label: Component Grid Settings

  grid_column_preset:
    label: Grid Column Preset
    extends: grid_column_preset  

  grid_column_start_class:
    extends: auf_grid/fields/grid_column_start_class
    width: 1/2
    when:
      grid_column_preset: grid__column--custom
  
  grid_column_end_class:
    extends: auf_grid/fields/grid_column_end_class
    width: 1/2
    when:
      grid_column_preset: grid__column--custom


  container_grid_settings:
    type: headline
    label: Container Component Grid Settings

  container_grid_type:
    type: select
    label: Sub-Grid Type
    default: grid
    options:
      grid: grid
      inline-grid: inline-grid

  container_inline_grid_items_span: 
    label: Inline Grid Items Span Class
    type: inline_grid_items_span_classes
    when: 
      container_grid_type: inline-grid