title: Site
# preset: pages
unlisted: true

tabs:
  pages:
    sections:
      subpages: 
        headline: Pages
        type: pages
        info: "[{{ page.intendedTemplate }}-template]"
        empty: No subpages yet


  settings:
    sections:
      grid_settings: auf_grid/grid_settings
  
  files:
    sections:
      files: 
        headline: Grid Test Files
        # https://getkirby.com/docs/reference/panel/sections/files
    